### ISSUE TITLE
Status Message is delayed or wrong often times

### ISSUE THREAD

**Issue by drstevebrulemd** [muhammadmuzzammil1998/BitcoinBot#19]
Is there any way to pull Bitfinex prices in the status message so they update every minute? I've noted that the price can be off by as much as 5-10 minutes+. For instance, it was showing $7300 for about a good 20 minutes before showing $7500.

**Comment by muhammadmuzzammil1998** [comment]
Thank you for taking your time to write to me about the problem.
### Why I am not using Bitfinex API to get prices
The main reason to not use Bitfinex API is that I don't use Bitfinex. Even if I did, it doesn't support many other real-life currency codes as symbols. The only currency code I could find on [documentation ](https://api.bitfinex.com/v1/symbols) are USD, JPY, GBP, and EUR. Now, I only use USD for the status price but I can't use it as discussed below.

### Not using Bitfinex for USD and setting it on the status
Well, the reason should be evident -- If a user asks for USD per BTC they are not gonna get the same price as the status and that's bad. Furthermore, I would have to manage two APIs which I can but it would increase the delay in response.

### Status price update problem
I think I know where the problem is. I think it is because the status update function only gets triggered whenever someone requests for the price. In your case, I think that the last request took place 20 minutes ago.
https://github.com/muhammadmuzzammil1998/BitcoinBot/blob/c5a69e4da3f955e52cdea15f9657d8176d7a766b/main.go#L74-L75
I will set it on an interval so the bot requests for the status to get updated every minute in the next release.

**Comment by drstevebrulemd** [comment]
> The main reason to not use Bitfinex API is that I don't use Bitfinex. Even if I did, it doesn't support many other real-life currency codes as symbols.

    Here's why Bitfinex is important. Like yourself, you probably trade on another exchange like Binance or GDAX possibly. Bitfinex sets the price that the majority of people follow. That and GDAX anyways, & most people follow the BTC/USD pair. 

    What I would recommend is allowing an option/setting for selecting either BFX/GDAX option, but ideally tracking BitFinex since those prices are the one the market uses. Why? Because whenever a major price change happens, it 9/10 times happens on Bitfinex first, and then the other exchanges like GDAX, or Binance follow accordingly _even though_  no one trades on Bitfinex, but this is how it is done.

**Comment by muhammadmuzzammil1998** [comment]
So, if I am able to understand you correctly, you want an option, like a flag (>btc -bfx), to get the details from Bitfinex?

If so, I can do that :)

**Comment by muhammadmuzzammil1998** [comment]
Sorry, I can't add bfx. 

Thanks!
